# Generated by Django 6.0.3 on 2026-04-08 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('jobseeker', 'Job Seeker'), ('recruiter', 'Recruiter')], max_length=25),
        ),
    ]
